### ISSUE TITLE
test example error

### ISSUE THREAD

**Issue by ChaoyiXie** [nie-lang/DeepImageStitching-1.0#1]
============
Traceback (most recent call last):
  File "inference.py", line 76, in <module>
    inference_func(pretrained_model)
  File "inference.py", line 64, in inference_func
    input_clip = np.expand_dims(input_loader.get_video_clips(i), axis=0)
  File "D:\Project\depth\DeepImageStitching-1.0-main\Codes\Stitch_Net\utils.py", line 74, in get_video_clips
    image = np_load_frame(video_info_list[i]['frame'][index], self._resize_height, self._resize_width)
IndexError: list index out of range

**Comment by nie-lang** [comment]
Maybe you can change the parameter 'length' to fit the length of the test examples. And please create the 'result' folder before you run 'inference.py'.

**Comment by gyh61916533** [comment]
May I ask if you have solved this error?
